---
- name: Allow loopback iface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  notify: save rules

- name: Drop invalid
  iptables:
    chain: "{{ item }}"
    ctstate: INVALID
    jump: ACCEPT
  become: yes
  with_items: [ 'INPUT', 'FORWARD' ]
  notify: save rules

- name: Allow related and established connections
  iptables:
    chain: '{{ item }}'
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  with_items: [ 'INPUT', 'FORWARD' ]
  notify: save rules

- name: Allow new incoming SYN packets on TCP port 22 (SSH).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '22'
    ctstate: NEW
    syn: match
    jump: ACCEPT
    in_interface: "{{ IFACE_LAN }}"
    comment: Accept new SSH connections.
  notify: save rules

- name: Allow forward from LAN to WAN interfaces
  iptables:
    chain: FORWARD
    in_interface: "{{ IFACE_LAN }}"
    out_interface: "{{ IFACE_WAN }}"
    jump: ACCEPT
  notify: save rules

- name: iptables nat
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ IFACE_WAN }}"
    jump: MASQUERADE
  notify: save rules

- name: Set the policy for the chain to DROP
  iptables:
    chain: "{{ item }}"
    policy: DROP
  with_items: [ 'INPUT', 'FORWARD' ]
  notify: save rules
