---
- name: Add repo
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Install docker
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"
